// © 2023 The mhfz-overlay developers.
// Use of this source code is governed by a MIT license that can be
// found in the LICENSE file.

namespace MHFZ_Overlay.Models.Collections;

using System.Collections.Generic;
using System.Collections.ObjectModel;

/// <summary>
/// The monster image list.
/// </summary>
public static class MonsterImages
{
    public static ReadOnlyDictionary<int, string> MonsterImageID { get; } = new (new Dictionary<int, string>
    {
        { 0, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/none.png" },
        { 1, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/rathian.png" },
        { 3, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/kelbi.png" },
        { 4, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/mosswine.png" },
        { 5, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/bullfango.png" },
        { 6, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/yian_kut-ku.png" },
        { 7, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/lao-shan_lung.png" },
        { 8, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/cephadrome.png" },
        { 9, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/felyne.png" },
        { 10, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 12, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/aptonoth.png" },
        { 13, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/genprey.png" },
        { 14, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/diablos.png" },
        { 16, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/velociprey.png" },
        { 18, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/felyne.png" },
        { 19, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/vespoid.png" },
        { 20, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/gypceros.png" },
        { 22, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/basarios.png" },
        { 23, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/melynx.png" },
        { 24, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/hornetaur.png" },
        { 25, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/apceros.png" },
        { 26, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/monoblos.png" },
        { 27, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/velocidrome.png" },
        { 28, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/gendrome.png" },
        { 29, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 30, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/ioprey.png" },
        { 31, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/iodrome.png" },
        { 32, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 33, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/kirin.png" },
        { 34, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/cephalos.png" },
        { 35, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/giaprey.png" },
        { 37, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/pink_rathian.png" },
        { 38, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/blue_yian_kut-ku.png" },
        { 39, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/purple_gypceros.png" },
        { 40, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/yian_garuga.png" },
        { 41, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/silver_rathalos.png" },
        { 42, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/gold_rathian.png" },
        { 43, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/black_diablos.png" },
        { 44, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/white_monoblos.png" },
        { 45, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/red_khezu.png" },
        { 46, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/green_plesioth.png" },
        { 47, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/black_gravios.png" },
        { 49, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/azure_rathalos.png" },
        { 50, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/ashen_lao-shan_lung.png" },
        { 52, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/congalala.png" },
        { 54, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/kushala_daora.png" },
        { 55, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/shen_gaoren.png" },
        { 56, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/great_thunderbug.png" },
        { 57, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/shakalaka.png" },
        { 58, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/yama_tsukami.png" },
        { 59, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/chameleos.png" },
        { 60, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/rusted_kushala_daora.png" },
        { 61, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/blango.png" },
        { 62, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/conga.png" },
        { 63, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/remobra.png" },
        { 64, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/lunastra.png" },
        { 66, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/hermitaur.png" },
        { 67, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/shogun_ceanataur.png" },
        { 68, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/bulldrome.png" },
        { 69, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/anteka.png" },
        { 70, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/popo.png" },
        { 72, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/yama_tsukami.png" },
        { 73, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/ceanataur.png" },
        { 75, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/lavasioth.png" },
        { 77, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/akantor.png" },
        { 78, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/bright_hypnoc.png" },
        { 79, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/red_lavasioth.png" },
        { 81, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/orange_espinas.png" },
        { 82, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/silver_hypnoc.png" },
        { 84, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/akura_jebia.png" },
        { 85, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/berukyurosu.png" },
        { 86, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/cactus.png" },
        { 87, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 88, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 90, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/white_espinas.png" },
        { 91, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/kamu_orugaron.png" },
        { 92, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/nono_orugaron.png" },
        { 93, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/raviente.png" },
        { 94, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/dyuragaua.png" },
        { 96, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/gurenzeburu.png" },
        { 97, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/burukku.png" },
        { 98, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/erupe.png" },
        { 101, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/gogomoa.png" },
        { 102, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/gogomoa.png" },
        { 104, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/abiorugu.png" },
        { 105, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/kuarusepusu.png" },
        { 108, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/rebidiora.png" },
        { 114, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/farunokku.png" },
        { 115, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/pokaradon.png" },
        { 117, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/pokara.png" },
        { 118, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 119, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/goruganosu.png" },
        { 120, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/aruganosu.png" },
        { 122, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/zerureusu.png" },
        { 123, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/gougarf.png" },
        { 124, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/uruki.png" },
        { 125, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/forokururu.png" },
        { 126, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/meraginasu.png" },
        { 127, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/diorex.png" },
        { 128, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/garuba_daora.png" },
        { 130, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/varusaburosu.png" },
        { 131, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/poborubarumu.png" },
        { 132, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/duremudira.png" },
        { 133, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 134, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/felyne.png" },
        { 135, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 136, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 137, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/cactus.png" },
        { 138, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 139, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/gureadomosu.png" },
        { 143, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/kusubami.png" },
        { 144, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/yama_kurai.png" },
        { 145, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/duremudira.png" },
        { 147, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/deviljho.png" },
        { 148, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/brachydios.png" },
        { 149, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/berserk_raviente.png" },
        { 150, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/toa_tesukatora.png" },
        { 151, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/barioth.png" },
        { 152, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/uragaan.png" },
        { 153, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/stygian_zinogre.png" },
        { 156, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 157, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 158, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/voljang.png" },
        { 159, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/nargacuga.png" },
        { 160, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/keoaruboru.png" },
        { 161, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/zenaserisu.png" },
        { 162, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/gore_magala.png" },
        { 163, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/blinking_nargacuga.png" },
        { 164, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/shagaru_magala.png" },
        { 165, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/amatsu.png" },
        { 167, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/arrogant_duremudira.png" },
        { 168, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 169, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/seregios.png" },
        { 170, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/zenith_bogabadorumu.gif" },
        { 171, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/random.png" },
        { 172, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/bombardier_bogabadorumu.png" },
        { 173, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/uruki.png" },
        { 174, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/sparkling_zerureusu.png" },
        { 175, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/pso2_rappy.png" },
        { 176, @"pack://application:,,,/MHFZ_Overlay;component/Assets/Icons/png/monster/king_shakalaka.png" },
    });
}
